{"name": "test_put_logged_in_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 200\n +  where 500 = <Response [500]>.status_code", "trace": "def test_put_logged_in_user():\n        \"\"\"\n        updates an existent user in the store\n        :return:\n        \"\"\"\n        response = requests.get(f\"{url}/user/theUser\", headers=header)\n>       assert response.status_code == 200\nE       assert 500 == 200\nE        +  where 500 = <Response [500]>.status_code\n\ntest.py:197: AssertionError"}, "description": "\n    updates an existent user in the store\n    :return:\n    ", "start": 1659615843359, "stop": 1659615843997, "uuid": "5b98f571-568a-4119-9e9d-5dc24da22bcc", "historyId": "81b12a8679f969196784975beedd26be", "testCaseId": "8de4ace2c44d9e705f424ae3bf955240", "fullName": "test#test_put_logged_in_user", "labels": [{"name": "suite", "value": "test"}, {"name": "host", "value": "DESKTOP-V80V9RG"}, {"name": "thread", "value": "22264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test"}]}